### ISSUE TITLE
pulsebert not reachable by local name after HTTPS change

### ISSUE THREAD

**Issue by strfry** [c3d2/nix-configs#1]
Unfortunately, caddy refuses to serve ympd on http://pulsebert/ after the recent caddy setup by @astro .

My attempted fix was to let ympd serve :80 and only proxy :443, but caddy doesn't seem to like this. I kept it at this state.

**Comment by Mic92** [comment]
`tls off` maybe? https://github.com/Mic92/dotfiles/blob/master/nixos/configuration.nix#L207

**Comment by strfry** [comment]
Apparently, caddy is unable to let go of Port 80: https://github.com/mholt/caddy/issues/504

But `tls off` under a second label `*:80` might just work. I just can't test it right away outside of HQ obviously...

**Comment by astro** [comment]
Caddy will now redirect `:80` to https://…
